const { GRAPH_TYPES } = require('../../core/constants/graphTypes');

const faceOptions = [
  { value: 'up', label: 'Сверху' },
  { value: 'down', label: 'Снизу' },
  { value: 'north', label: 'Север' },
  { value: 'south', label: 'Юг' },
  { value: 'east', label: 'Восток' },
  { value: 'west', label: 'Запад' },
];

const worldNodes = [
  {
    type: 'world:find_block',
    label: '🔎 Найти блок',
    category: 'Мир',
    description: 'Ищет блоки по имени в загруженных чанках. Возраст 7 — спелые пшеница, морковь и картофель. Возраст 3 — свёкла и адский нарост.',
    graphType: GRAPH_TYPES.ALL,
    executor: require('../../core/nodes/world/find_block').execute,
    evaluator: require('../../core/nodes/world/find_block').evaluate,
    computeInputs: () => [
      { id: 'exec', name: 'Выполнить', type: 'Exec' },
      { id: 'name', name: 'Имя блока', type: 'String', required: true, inlineField: true, placeholder: 'wheat' },
      { id: 'radius', name: 'Радиус', type: 'Number', required: false, inlineField: true, placeholder: '16' },
      { id: 'count', name: 'Сколько', type: 'Number', required: false, inlineField: true, placeholder: '1' },
      { id: 'minAge', name: 'Мин. возраст', type: 'Number', required: false, inlineField: true, placeholder: '7' },
    ],
    computeOutputs: () => [
      { id: 'exec', name: 'Нашёл', type: 'Exec' },
      { id: 'exec_failed', name: 'Не нашёл', type: 'Exec' },
      { id: 'block', name: 'Блок', type: 'Object' },
      { id: 'blocks', name: 'Блоки', type: 'Array' },
      { id: 'x', name: 'X', type: 'Number' },
      { id: 'y', name: 'Y', type: 'Number' },
      { id: 'z', name: 'Z', type: 'Number' },
      { id: 'name', name: 'Имя', type: 'String' },
      { id: 'age', name: 'Возраст', type: 'Number' },
      { id: 'success', name: 'Успех?', type: 'Boolean' },
    ],
    defaultData: { name: 'wheat', radius: 16, count: 1, minAge: null },
    theme: { headerColor: '#0f766e', accentColor: '#14b8a6' },
  },
  {
    type: 'world:dig',
    label: '⛏️ Сломать блок',
    category: 'Мир',
    description: 'Ломает блок по объекту или координатам. Если блок далеко, бот сначала подходит.',
    graphType: GRAPH_TYPES.ALL,
    executor: require('../../core/nodes/world/dig').execute,
    evaluator: require('../../core/nodes/world/dig').evaluate,
    computeInputs: () => [
      { id: 'exec', name: 'Выполнить', type: 'Exec' },
      { id: 'block', name: 'Блок', type: 'Object', required: false },
      { id: 'x', name: 'X', type: 'Number', required: false, inlineField: true, placeholder: '0' },
      { id: 'y', name: 'Y', type: 'Number', required: false, inlineField: true, placeholder: '64' },
      { id: 'z', name: 'Z', type: 'Number', required: false, inlineField: true, placeholder: '0' },
    ],
    computeOutputs: () => [
      { id: 'exec', name: 'Сломал', type: 'Exec' },
      { id: 'exec_failed', name: 'Не удалось', type: 'Exec' },
      { id: 'success', name: 'Успех?', type: 'Boolean' },
    ],
    defaultData: { x: null, y: null, z: null },
    theme: { headerColor: '#d97706', accentColor: '#f59e0b' },
  },
  {
    type: 'world:place',
    label: '🧱 Поставить блок',
    category: 'Мир',
    description: 'Ставит предмет из руки на грань блока. Семена пшеницы — wheat_seeds на верх грядки.',
    graphType: GRAPH_TYPES.ALL,
    executor: require('../../core/nodes/world/place').execute,
    evaluator: require('../../core/nodes/world/place').evaluate,
    computeInputs: () => [
      { id: 'exec', name: 'Выполнить', type: 'Exec' },
      { id: 'block', name: 'Блок', type: 'Object', required: false },
      { id: 'x', name: 'X', type: 'Number', required: false, inlineField: true, placeholder: '0' },
      { id: 'y', name: 'Y', type: 'Number', required: false, inlineField: true, placeholder: '63' },
      { id: 'z', name: 'Z', type: 'Number', required: false, inlineField: true, placeholder: '0' },
      {
        id: 'face',
        name: 'Грань',
        type: 'String',
        required: false,
        inlineField: true,
        inlineFieldType: 'select',
        defaultValue: 'up',
        inlineFieldOptions: faceOptions,
      },
      { id: 'itemName', name: 'Предмет', type: 'String', required: false, inlineField: true, placeholder: 'wheat_seeds' },
    ],
    computeOutputs: () => [
      { id: 'exec', name: 'Поставил', type: 'Exec' },
      { id: 'exec_failed', name: 'Не удалось', type: 'Exec' },
      { id: 'x', name: 'X', type: 'Number' },
      { id: 'y', name: 'Y', type: 'Number' },
      { id: 'z', name: 'Z', type: 'Number' },
      { id: 'success', name: 'Успех?', type: 'Boolean' },
    ],
    defaultData: { x: null, y: null, z: null, face: 'up', itemName: '' },
    theme: { headerColor: '#15803d', accentColor: '#22c55e' },
  },
  {
    type: 'world:attack',
    label: '👊 Ударить',
    category: 'Мир',
    description: 'Один удар по сущности. Если она дальше 3 блоков, бот сначала подходит.',
    graphType: GRAPH_TYPES.ALL,
    executor: require('../../core/nodes/world/attack').execute,
    evaluator: require('../../core/nodes/world/attack').evaluate,
    computeInputs: () => [
      { id: 'exec', name: 'Выполнить', type: 'Exec' },
      { id: 'entity', name: 'Сущность', type: 'Object', required: true },
    ],
    computeOutputs: () => [
      { id: 'exec', name: 'Ударил', type: 'Exec' },
      { id: 'exec_failed', name: 'Не удалось', type: 'Exec' },
      { id: 'success', name: 'Успех?', type: 'Boolean' },
    ],
    defaultData: {},
    theme: { headerColor: '#dc2626', accentColor: '#ef4444' },
  },
];

module.exports = worldNodes;
