name: 🚀 Предложение по улучшению (Feature Request)
description: Предложите новую идею или улучшение
title: "[Feature] Краткое описание улучшения"
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Чтобы мы могли быстрее понять вашу идею, пожалуйста, предоставьте как можно больше деталей.

  - type: textarea
    id: feature-description
    attributes:
      label: Опишите ваше предложение
      description: Четко и кратко опишите, как бы вы хотели, чтобы это работало.
    validations:
      required: true