const CATEGORY_ALIASES = {
  data: 'data',
  'данные': 'data',
  flow: 'flow',
  'поток': 'flow',
  math: 'math',
  'математика': 'math',
  logic: 'logic',
  'логика': 'logic',
  string: 'string',
  strings: 'string',
  'строки': 'string',
  array: 'array',
  arrays: 'array',
  'массив': 'array',
  'массивы': 'array',
  object: 'object',
  objects: 'object',
  'объект': 'object',
  'объекты': 'object',
  action: 'action',
  actions: 'action',
  'действия': 'action',
  time: 'time',
  'время': 'time',
  user: 'user',
  users: 'user',
  'пользователи': 'user',
  type: 'type',
  types: 'type',
  'типы': 'type',
  bot: 'bot',
  'бот': 'bot',
  debug: 'debug',
  'отладка': 'debug',
  inventory: 'inventory',
  'инвентарь': 'inventory',
  navigation: 'navigation',
  'навигация': 'navigation',
  container: 'container',
  containers: 'container',
  'контейнеры': 'container',
  furnace: 'furnace',
  'печка': 'furnace',
  event: 'event',
  events: 'event',
  'события': 'event',
  websocket: 'websocket',
  'websocket api': 'websocket',
};

export function normalizeVisualEditorCategory(category = '') {
  const normalized = String(category).trim().toLowerCase();
  return CATEGORY_ALIASES[normalized] || normalized;
}
